// Builds dist/tokens.css and dist/tokens.flat.json from tokens/*.json (W3C DTCG format).
// No dependencies: `node build-tokens.mjs`. Swap for Style Dictionary once the RD stack is decided.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const load = f => JSON.parse(readFileSync(join(root, 'tokens', f), 'utf8'));

const base = load('base.json');
const component = load('component.json');
const light = load('theme.light.json');
const dark = load('theme.dark.json');

// Collect leaf tokens as { path: 'a.b.c', value, type, description }
function flatten(node, path = [], inheritedType, out = []) {
  const type = node.$type ?? inheritedType;
  if ('$value' in node) {
    out.push({ path: path.join('.'), value: node.$value, type, description: node.$description });
    return out;
  }
  for (const [k, v] of Object.entries(node)) {
    if (!k.startsWith('$') && v && typeof v === 'object') flatten(v, [...path, k], type, out);
  }
  return out;
}

const baseTokens = flatten(base);
const lightTokens = flatten(light);
const darkTokens = flatten(dark);
const componentTokens = flatten(component);
const lookup = new Map([...baseTokens, ...lightTokens].map(t => [t.path, t]));

// Base shadows are only reachable through theme.shadow.* so each theme can redefine them.
const isHiddenBase = t => t.path.startsWith('shadow.') || t.path.startsWith('breakpoint.');
const varName = path => '--' + path.replace(/^theme\./, '').replace(/\./g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

function format(value, type) {
  if (Array.isArray(value) && type === 'fontFamily') {
    return value.map(f => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
  }
  if (Array.isArray(value) && type === 'cubicBezier') return `cubic-bezier(${value.join(', ')})`;
  return String(value);
}

// References become var(...) so themes can swap them at runtime.
function cssValue(t) {
  const v = format(t.value, t.type);
  return v.replace(/\{([^}]+)\}/g, (_, ref) => {
    const target = lookup.get(ref);
    if (!target) throw new Error(`Unknown reference {${ref}} in ${t.path}`);
    return isHiddenBase(target) ? cssValue(target) : `var(${varName(ref)})`;
  });
}

// Fully resolved values for the flat JSON export.
function resolve(t, tokens) {
  const map = new Map([...baseTokens, ...tokens].map(x => [x.path, x]));
  const v = format(t.value, t.type);
  return v.replace(/\{([^}]+)\}/g, (_, ref) => resolve(map.get(ref), tokens));
}

const block = (selector, tokens) =>
  `${selector} {\n${tokens.map(t => `  ${varName(t.path)}: ${cssValue(t)};`).join('\n')}\n}\n`;

const breakpoints = baseTokens.filter(t => t.path.startsWith('breakpoint.'));
const css = `/* Generated by build-tokens.mjs — do not edit by hand. Source: design-system/tokens/*.json */

/* Breakpoints (CSS variables cannot be used in media queries; copy these values):
${breakpoints.map(b => ` *   ${b.path.split('.')[1].padEnd(3)} max-width: ${b.value}${b.description ? ' — ' + b.description : ''}`).join('\n')}
 */

/* Primitives */
${block(':root', baseTokens.filter(t => !isHiddenBase(t)))}
/* Light theme (default) */
${block(':root,\n[data-theme="light"]', lightTokens)}
/* Dark theme (draft — not yet validated on screens) */
${block('[data-theme="dark"]', darkTokens)}
/* To follow the OS setting later, wrap the dark block in:
   @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { ... } } */

/* Components */
${block(':root', componentTokens)}`;

const flat = {
  light: Object.fromEntries([...baseTokens.filter(t => !t.path.startsWith('shadow.')), ...lightTokens, ...componentTokens]
    .map(t => [t.path.replace(/^theme\./, ''), resolve(t, lightTokens)])),
  dark: Object.fromEntries(darkTokens.map(t => [t.path.replace(/^theme\./, ''), resolve(t, darkTokens)])),
};

// ---------- Tailwind CSS v4 theme ----------
// Semantic token → Tailwind color name, so utilities read as bg-canvas, text-fg-secondary, border-line-subtle.
const TW_COLORS = {
  'bg.app': 'app', 'bg.canvas': 'canvas', 'bg.surface': 'surface', 'bg.raised': 'raised', 'bg.field': 'field',
  'bg.hover': 'hover', 'bg.selected': 'selected', 'bg.overlay': 'overlay',
  'text.primary': 'fg', 'text.secondary': 'fg-secondary', 'text.tertiary': 'fg-tertiary',
  'text.placeholder': 'fg-placeholder', 'text.disabled': 'fg-disabled', 'text.inverse': 'fg-inverse',
  'icon.default': 'icon', 'icon.muted': 'icon-muted',
  'border.subtle': 'line-subtle', 'border.default': 'line', 'border.strong': 'line-strong', 'border.focus': 'line-focus',
  'focus.ring': 'focus-ring',
  'action.primary.bg': 'primary', 'action.primary.bgHover': 'primary-hover', 'action.primary.fg': 'on-primary',
  'action.secondary.bg': 'secondary', 'action.secondary.bgHover': 'secondary-hover',
  'action.secondary.border': 'secondary-line', 'action.secondary.fg': 'on-secondary',
  'action.disabled.bg': 'disabled', 'action.disabled.fg': 'on-disabled',
  'status.success.fg': 'success', 'status.success.icon': 'success-icon', 'status.success.bg': 'success-soft',
  'status.danger.fg': 'danger', 'status.danger.bg': 'danger-soft',
  'status.warning.fg': 'warning', 'status.warning.bg': 'warning-soft',
  'status.info.fg': 'info', 'status.info.bg': 'info-soft',
};
const L = flat.light, D = flat.dark;
const pick = prefix => Object.entries(L).filter(([k]) => k.startsWith(prefix));
const ginaVar = path => '--gina-' + path.replace(/\./g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
const themed = Object.keys(D);
const runtime = (values) => themed.map(p => `  ${ginaVar(p)}: ${values[p]};`).join('\n');
const textLeading = { 12: 1.5, 13: 1.5, 14: 1.5, 15: 1.8, 16: 1.5, 18: 1.3, 26: 1.3, 28: 1.3 };

const tailwind = `/* Generated by build-tokens.mjs — do not edit by hand. Source: design-system/tokens/*.json
 *
 * Tailwind CSS v4 theme for Gina. In your main CSS:
 *   @import "tailwindcss";
 *   @import "./gina-theme.css";
 *
 * Tailwind's default palette, radii, shadows, font sizes and breakpoints are reset,
 * so only Gina tokens are available (bg-canvas, text-fg-secondary, rounded-md, shadow-lg, text-14 …).
 * Spacing keeps Tailwind's 4px scale, which matches Gina's space tokens: space-2h = 2.5, space-3h = 3.5.
 * Breakpoints are desktop-first in DESIGN.md: use max-md: and max-sm: variants.
 */

@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));

@theme {
  --color-*: initial;
  --radius-*: initial;
  --shadow-*: initial;
  --text-*: initial;
  --breakpoint-*: initial;
  --font-*: initial;
  --leading-*: initial;
  --ease-*: initial;

  --color-brand-giant: ${L['color.brand.giant']};

  --font-sans: ${L['font.family.sans']};
  --font-mono: ${L['font.family.mono']};
${pick('font.weight.').map(([k, v]) => `  --font-weight-${k.split('.').pop().replace('regular', 'normal')}: ${v};`).join('\n')}

${pick('font.size.').map(([k, v]) => { const n = k.split('.').pop(); return `  --text-${n}: ${v};\n  --text-${n}--line-height: ${textLeading[n]};`; }).join('\n')}

${pick('font.lineHeight.').map(([k, v]) => `  --leading-${k.split('.').pop()}: ${v};`).join('\n')}

${pick('radius.').filter(([k]) => !k.endsWith('.full')).map(([k, v]) => `  --radius-${k.split('.').pop()}: ${v};`).join('\n')}

${pick('breakpoint.').map(([k, v]) => `  --breakpoint-${k.split('.').pop()}: ${v};`).join('\n')}

  --container-sidebar: ${L['layout.sidebarWidth']};
  --container-sidebar-md: ${L['layout.sidebarWidthMd']};
  --container-sidebar-sm: ${L['layout.sidebarWidthSm']};
  --container-chat: ${L['layout.chatMaxWidth']};
  --container-ai-bubble: ${L['layout.aiBubbleMaxWidth']};
  --container-user-bubble: ${L['layout.userBubbleMaxWidth']};
  --container-hero: ${L['layout.heroMaxWidth']};
  --container-popover: ${L['layout.popoverWidth']};
  --container-drawer: ${L['layout.drawerWidth']};
  --container-menu: ${L['layout.menuWidth']};

  --ease-standard: ${L['motion.easing.standard']};
  --ease-out: ${L['motion.easing.out']};
}

/* Theme-dependent values: utilities point at the --gina-* variables below, so switching data-theme needs no class changes. */
@theme inline {
${Object.entries(TW_COLORS).map(([p, n]) => `  --color-${n}: var(${ginaVar(p)});`).join('\n')}
${pick('shadow.').map(([k]) => `  --shadow-${k.split('.').pop()}: var(${ginaVar(k)});`).join('\n')}
}

:root,
[data-theme="light"] {
${runtime(L)}
}

/* Dark theme (draft — not yet validated on screens) */
[data-theme="dark"] {
${runtime(D)}
}

/* Non-theme tokens used with arbitrary values, e.g. z-(--z-popover), h-(--component-button-height) */
:root {
${pick('z.').map(([k, v]) => `  --${k.replace(/\./g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()}: ${v};`).join('\n')}
${pick('layout.').map(([k, v]) => `  --${k.replace(/\./g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()}: ${v};`).join('\n')}
${pick('motion.duration.').map(([k, v]) => `  --${k.replace(/\./g, '-')}: ${v};`).join('\n')}
${componentTokens.map(t => `  ${varName(t.path)}: ${L[t.path]};`).join('\n')}
}
`;

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist', 'tokens.css'), css);
writeFileSync(join(root, 'dist', 'tokens.flat.json'), JSON.stringify(flat, null, 2) + '\n');
writeFileSync(join(root, 'dist', 'gina-theme.css'), tailwind);
console.log(`tokens.css: ${baseTokens.length + lightTokens.length + componentTokens.length} light, ${darkTokens.length} dark tokens; gina-theme.css for Tailwind v4`);
